# Generated by Django 2.1.2 on 2018-10-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181027_0504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Noticelist',
        ),
    ]
