# Generated by Django 2.1.2 on 2018-10-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181027_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelist',
            name='date_expiry',
            field=models.DateField(),
        ),
    ]
